-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: sql301.infinityfree.com
-- Generation Time: Mar 02, 2025 at 10:52 AM
-- Server version: 10.6.19-MariaDB
-- PHP Version: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `if0_38428339_maharishi`
--

-- --------------------------------------------------------

--
-- Table structure for table `maharishis`
--

CREATE TABLE `maharishis` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `title` char(100) NOT NULL,
  `description` text NOT NULL,
  `image` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `maharishis`
--

INSERT INTO `maharishis` (`id`, `name`, `slug`, `title`, `description`, `image`) VALUES
(1, 'Agastya', 'agastya', '<h1>Agastya - The Revered Sage</h1>', '<p>Agastya is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian culture. Here\\\'s some key information about Agastya:</p><h2>Life and Legends</h2><p>Agastya was born to the divine sage <strong>Mitra-Varuna</strong> and the <strong>Apsara</strong> (celestial nymph) Urvashi. He is often depicted as a short, stout man with a prominent belly.</p><h2>Contributions</h2><ul><li><strong>Vedic Wisdom:</strong> Agastya is credited with composing several hymns in the <em>Rigveda</em>, one of Hinduism\\\'s most sacred texts.</li><li><strong>Tamil Language:</strong> He is said to have created the Tamil language and written the first Tamil grammar book, <em>Agattiyam</em>.</li><li><strong>Ayurveda:</strong> Agastya is associated with the development of Ayurveda, the traditional Indian system of medicine.</li></ul><h2>Spiritual Significance</h2><ul><li><strong>Saptarishis:</strong> Agastya is considered one of the seven sages (<em>Saptarishis</em>) who have guided humanity throughout history.</li><li><strong>Guru:</strong> He is revered as a spiritual guru, offering guidance on the path to enlightenment.</li><li><strong>Cosmic Balance:</strong> Agastya is believed to have maintained cosmic balance by consuming the demon <em>Vatapi</em>, who threatened the gods.</li></ul><h2>Worship and Legacy</h2><ul><li><strong>Temples:</strong> Agastya is worshipped in several temples across India, particularly in the southern states of Tamil Nadu and Kerala.</li><li><strong>Festivals:</strong> His birthday, <em>Agastya Jayanti</em>, is celebrated with great fervor in some parts of India,</li><li><strong>Influence on Culture:</strong> Agastya\\\'s contributions to Tamil language, literature, and culture have had a lasting impact on Indian heritage.</li></ul><p>Agastya\\\'s life and legacy continue to inspire and guide people on their spiritual journeys.</p>', 'Agastya.jpg'),
(2, 'Atri', 'atri', '<h1>Atri - The Revered Sage</h1>', '<p>Atri is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian culture. Here\'s some key information about Atri:</p>    <h2>Life and Legends</h2>    <p>Atri was born to the divine sage <strong>Brahma</strong> and is considered one of the seven sages (<em>Saptarishis</em>) who have guided humanity throughout history. He is often depicted as a wise and powerful sage with a long beard.</p>    <h2>Contributions</h2>    <ul>      <li><strong>Vedic Wisdom:</strong> Atri is credited with composing several hymns in the <em>Rigveda</em>, one of Hinduism\'s most sacred texts.</li>        <li><strong>Ayurveda:</strong> He is associated with the development of Ayurveda, the traditional Indian system of medicine.</li>        <li><strong>Spiritual Guidance:</strong> Atri is revered as a spiritual guru, offering guidance on the path to enlightenment.</li> </ul>    <h2>Family and Descendants</h2>    <ul>       <li><strong>Wife:</strong> Atri\'s wife was <em>Anasuya</em>, a pious and devoted woman who was known for her extraordinary spiritual powers.</li>  <li><strong>Sons:</strong> Atri and Anasuya had three sons: <em>Dattatreya, Durvasa,</em> and <em>Chandra</em>.</li>   <li><strong>Descendants:</strong> Atri\'s descendants are considered to be the <em>Atri clan</em>, which includes many notable sages and seers in Hindu mythology.</li>  </ul>   <h2>Worship and Legacy</h2>  <ul>    <li><strong>Temples:</strong> Atri is worshipped in several temples across India, particularly in the states of Maharashtra and Gujarat.</li>       <li><strong>Festivals:</strong> His birthday, <em>Atri Jayanti</em>, is celebrated with great fervor in some parts of India.</li>   <li><strong>Influence on Culture:</strong> Atri\'s contributions to Hindu mythology, Ayurveda, and spiritual guidance have had a lasting impact on Indian heritage.</li> </ul>    <p>Atri\'s life and legacy continue to inspire and guide people on their spiritual journeys.</p>', 'Atri.jpg'),
(3, 'Ashtavakra', 'ashtavakra', '<h1>Ashtavakra - The Revered Sage</h1>', '<p>Ashtavakra is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian philosophy. Here\\\'s some key information about Ashtavakra:</p> <h2>Life and Legends</h2>   <p>Ashtavakra was born with eight physical deformities (<em>ashta-vakra</em> means \\\"eight bends\\\" in Sanskrit), which made him an outcast in society. Despite his physical limitations, he possessed extraordinary spiritual powers and wisdom.</p>   <h2>Contributions</h2>    <ul> <li><strong>Ashtavakra Gita:</strong> Ashtavakra is credited with composing the <em>Ashtavakra Gita</em>, a sacred text that explores the nature of reality, the self, and the path to enlightenment.</li>       <li><strong>Advaita Vedanta:</strong> His teachings are rooted in <em>Advaita Vedanta</em>, a school of Hindu philosophy that emphasizes the non-dual nature of reality.</li>        <li><strong>Spiritual Guidance:</strong> Ashtavakra is revered as a spiritual guru, offering guidance on the path to self-realization and enlightenment.</li>  </ul>   <h2>Meeting with King Janaka</h2>    <p>Ashtavakra\\\'s most famous encounter was with <strong>King Janaka</strong>, a powerful and wise ruler who was seeking spiritual guidance. Ashtavakra\\\'s teachings had a profound impact on King Janaka, who eventually attained enlightenment.</p>    <h2>Teachings and Philosophy</h2>    <p>Ashtavakra\\\'s teachings emphasize the importance of:</p>    <ul>    <li><strong>Self-inquiry:</strong> Investigating the nature of the self and reality.</li>        <li><strong>Non-dualism:</strong> Recognizing the non-dual nature of reality, beyond distinctions and separations.</li>       <li><strong>Detachment:</strong> Letting go of attachments and desires that bind us to the material world.</li>    </ul>   <h2>Legacy and Influence</h2>    <p>Ashtavakra\\\'s teachings have had a profound impact on Hindu philosophy and spirituality, influencing many notable sages and philosophers, including <strong>Adi Shankara</strong>. His legacy continues to inspire seekers of truth and self-realization.</p>', '1740906741_Ashtavakra.jpg'),
(4, 'Kapila', 'kapila', '&lt;h1&gt;Kapila - The Revered Sage&lt;/h1&gt;', '<p>Kapila is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian philosophy. Here\'s some key information about Kapila:</p> <h2>Life and Legends</h2> <p>Kapila was born to the sage <strong>Kardama</strong> and his wife, <strong>Devahuti</strong>. He is considered one of the seven sages (<em>Saptarishis</em>) who have guided humanity throughout history.</p><h2>Contributions</h2> <ul> <li><strong>Sankhya Philosophy:</strong> Kapila is credited with developing the <em>Sankhya</em> philosophy, one of the six orthodox schools of Hindu philosophy. Sankhya emphasizes the dual nature of reality, comprising <em>purusha</em> (consciousness) and <em>prakriti</em> (matter).</li> <li><strong>Mahabharata:</strong> Kapila appears in the <em>Mahabharata</em>, where he plays a significant role in the story of King Sagara and the descent of the Ganges River.</li> <li><strong>Spiritual Guidance:</strong> Kapila is revered as a spiritual guru, offering guidance on the path to self-realization and enlightenment.</li> </ul><h2>Meeting with Devahuti</h2> <p>Kapila\'s most famous encounter was with his mother, <strong>Devahuti</strong>, who sought his guidance on spiritual matters. Kapila\'s teachings had a profound impact on Devahuti, who eventually attained enlightenment.</p> <h2>Teachings and Philosophy</h2> <p>Kapila\'s teachings emphasize the importance of:</p> <ul> <li><strong>Discrimination:</strong> Distinguishing between the eternal and the ephemeral, the self and the non-self.</li> <li><strong>Detachment:</strong> Letting go of attachments and desires that bind us to the material world.</li> <li><strong>Self-realization:</strong> Recognizing the true nature of the self and reality.</li> </ul> <h2>Legacy and Influence</h2> <p>Kapila\'s teachings have had a profound impact on Hindu philosophy and spirituality, influencing many notable sages and philosophers, including <strong>Adi Shankara</strong>. His legacy continues to inspire seekers of truth and self-realization.</p>', 'Kapila.jpg'),
(5, 'Kardama', 'kardama', '&lt;h1&gt;Kardama - The Revered Sage&lt;/h1&gt;', '<p>Kardama is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian mythology. Here\\\'s some key information about Kardama:</p> <h2>Life and Legends</h2> <p>Kardama was a powerful sage who lived in ancient India. He was a <strong>Brahmarishi</strong> (a sage with divine powers) and was known for his extraordinary spiritual abilities.</p> <h2>Marriage and Children</h2> <p>Kardama was married to <strong>Devahuti</strong>, a princess from the kingdom of Svarocisa. They had nine daughters, including Kapila\\\'s mother, and one son, <strong>Kapila</strong>.</p> <h2>Contributions</h2> <ul> <li><strong>Sage and Scholar:</strong> Kardama was a renowned sage and scholar who possessed deep knowledge of the Vedas and other sacred texts.</li> <li><strong>Spiritual Guidance:</strong> He was a spiritual guide who offered wisdom to those seeking enlightenment.</li> <li><strong>Prajapati:</strong> Kardama was also considered a <em>Prajapati</em>, a creator deity responsible for creating and sustaining life on earth.</li> </ul> <h2>Meeting with Lord Vishnu</h2> <p>Kardama is said to have met <strong>Lord Vishnu</strong>, who appeared before him in his divine form. Lord Vishnu blessed Kardama and granted him a boon, which he used to request the birth of a son who would be a great sage and guide humanity.</p> <h2>Teachings and Philosophy</h2> <p>Kardama\\\'s teachings emphasize the importance of:</p> <ul> <li><strong>Spiritual Growth:</strong> Pursuing spiritual growth and self-realization through meditation, yoga, and other spiritual practices.</li> <li><strong>Detachment:</strong> Letting go of attachments and desires that bind us to the material world.</li> <li><strong>Selfless Service:</strong> Engaging in selfless service and helping others without expectation of reward or recognition.</li> </ul> <h2>Legacy and Influence</h2> <p>Kardama\\\'s legacy continues to inspire seekers of truth and self-realization. His teachings and philosophy have had a profound impact on Hindu mythology and spirituality.</p>', 'Kardama.jpg'),
(6, 'Kashyapa', 'kashyapa', '&lt;h1&gt;Kashyapa - The Revered Sage&lt;/h1&gt;', '<p>Kashyapa is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian mythology. Here\\\'s some key information about Kashyapa:</p> <h2>Life and Legends</h2> <p>Kashyapa was a powerful sage who lived in ancient India. He was a <strong>Brahmarishi</strong> (a sage with divine powers) and was known for his extraordinary spiritual abilities.</p> <h2>Family and Descendants</h2> <p>Kashyapa was married to multiple wives, including:</p> <ul> <li><strong>Aditi:</strong> Mother of the Devas (gods)</li> <li><strong>Diti:</strong> Mother of the Daityas (demons)</li> <li><strong>Danu:</strong> Mother of the Danavas (demons)</li> <li><strong>Kadru:</strong> Mother of the Nagas (serpents)</li> <li><strong>Vinata:</strong> Mother of Garuda (the eagle) and Aruna (the charioteer of the sun)</li> </ul> <p>Kashyapa\\\'s descendants include many notable figures in Hindu mythology, including the gods, demons, and serpents.</p> <h2>Contributions</h2> <ul> <li><strong>Vedic Wisdom:</strong> Kashyapa was a renowned sage who possessed deep knowledge of the Vedas and other sacred texts.</li> <li><strong>Spiritual Guidance:</strong> He was a spiritual guide who offered guidance and wisdom to those seeking enlightenment.</li> <li><strong>Cosmic Creation:</strong> Kashyapa is said to have played a role in the creation of the universe, helping to populate the earth with various beings.</li> </ul> <h2>Teachings and Philosophy</h2> <p>Kashyapa\\\'s teachings emphasize the importance of:</p> <ul> <li><strong>Dharma:</strong> Living a righteous and virtuous life</li> <li><strong>Self-control:</strong> Controlling one\\\'s desires and emotions</li> <li><strong>Compassion:</strong> Showing kindness and compassion to all living beings</li> </ul> <h2>Legacy and Influence</h2> <p>Kashyapa\\\'s legacy continues to inspire seekers of truth and self-realization. His teachings and philosophy have had a profound impact on Hindu mythology and spirituality.</p>', 'Kashyapa.jpg'),
(7, 'Bhrigu', 'bhrigu', '&lt;h1&gt;Bhrigu - The Revered Sage&lt;/h1&gt;', '<p>Bhrigu is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian mythology and astrology.</p> <h2>Life and Legends</h2> <p>Bhrigu was a powerful sage who lived in ancient India. He was a <strong>Brahmarishi</strong> (a sage with divine powers) and was known for his extraordinary spiritual abilities.</p> <h2>Contributions</h2> <ul> <li><strong>Vedic Wisdom:</strong> Bhrigu was a renowned sage who possessed deep knowledge of the Vedas and other sacred texts.</li> <li><strong>Bhrigu Samhita:</strong> He is credited with composing the <em>Bhrigu Samhita</em>, an ancient Hindu text that deals with astrology, palmistry, and other forms of divination.</li> <li><strong>Manu Smriti:</strong> Bhrigu is also mentioned in the <em>Manu Smriti</em>, an ancient Hindu text that deals with law, ethics, and governance.</li> </ul> <h2>Astrological Contributions</h2> <p>Bhrigu is considered one of the most important sages in Hindu astrology. He is credited with:</p> <ul> <li><strong>Bhrigu Nadi:</strong> Developing the <em>Bhrigu Nadi</em> system of astrology, which is still used today.</li> <li><strong>Predictive Astrology:</strong> Bhrigu is said to have possessed the ability to predict future events with great accuracy.</li> </ul> <h2>Teachings and Philosophy</h2> <p>Bhrigu\\\'s teachings emphasize the importance of:</p> <ul> <li><strong>Self-realization:</strong> Attaining spiritual enlightenment and self-awareness.</li> <li><strong>Dharma:</strong> Living a righteous and virtuous life.</li> <li><strong>Karma:</strong> Understanding the law of karma and its effects on human life.</li> </ul> <h2>Legacy and Influence</h2> <p>Bhrigu\\\'s legacy continues to inspire seekers of truth and self-realization. His teachings and philosophy have had a profound impact on Hindu mythology, astrology, and spirituality.</p>', 'Bhrigu.webp'),
(8, 'Angira', 'angira', '&lt;h1&gt;Angira - The Revered Sage&lt;/h1&gt;', '<p>Angira is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian mythology and Vedic literature.</p> <h2>Life and Legends</h2> <p>Angira was a powerful sage who lived in ancient India. He was a <strong>Brahmarishi</strong> (a sage with divine powers) and was known for his extraordinary spiritual abilities.</p> <h2>Contributions</h2> <ul> <li><strong>Vedic Literature:</strong> Angira is credited with composing several hymns and verses in the <em>Rigveda</em>, one of the most sacred texts of Hinduism.</li> <li><strong>Angirasa:</strong> He is also associated with the <em>Angirasa</em>, a group of sages known for their wisdom, spiritual powers, and contributions to Vedic literature.</li> <li><strong>Spiritual Guidance:</strong> Angira was a spiritual guide who offered wisdom and enlightenment to seekers.</li> </ul> <h2>Teachings and Philosophy</h2> <p>Angira\\\'s teachings emphasize the importance of:</p> <ul> <li><strong>Self-realization:</strong> Attaining spiritual enlightenment and self-awareness.</li> <li><strong>Dharma:</strong> Living a righteous and virtuous life.</li> <li><strong>Yoga:</strong> Practicing yoga and meditation to attain spiritual growth and self-realization.</li> </ul> <h2>Legacy and Influence</h2> <p>Angira\\\'s legacy continues to inspire seekers of truth and self-realization. His teachings and philosophy have had a profound impact on Hindu mythology, Vedic literature, and spirituality.</p> <h2>Interesting Facts</h2> <ul> <li><strong>Name Meaning:</strong> The name <em>\\\"Angira\\\"</em> means \\\"fiery\\\" or \\\"radiant\\\" in Sanskrit.</li> <li><strong>Association with Agni:</strong> Angira is often associated with <em>Agni</em>, the Hindu god of fire, and is said to have possessed the power to control fire.</li> <li><strong>Mention in Mahabharata:</strong> Angira is mentioned in the <em>Mahabharata</em>, one of the most sacred texts of Hinduism.</li> </ul>', 'Angira.webp'),
(9, 'Pulastya', 'pulastya', '&lt;h1&gt;Pulastya - The Revered Sage&lt;/h1&gt;', '<p>Pulastya is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian mythology and Vedic literature.</p> <h2>Life and Legends</h2> <p>Pulastya was a powerful sage who lived in ancient India. He was a <strong>Brahmarishi</strong> (a sage with divine powers) and was known for his extraordinary spiritual abilities.</p> <h2>Contributions</h2> <ul> <li><strong>Vedic Literature:</strong> Pulastya is credited with composing several hymns and verses in the <em>Rigveda</em>, one of the most sacred texts of Hinduism.</li> <li><strong>Pulastya Gotra:</strong> He is associated with the <em>Pulastya Gotra</em>, a lineage of sages and scholars known for their wisdom and spiritual powers.</li> <li><strong>Spiritual Guidance:</strong> Pulastya was a spiritual guide who offered wisdom and enlightenment to seekers.</li> </ul> <h2>Teachings and Philosophy</h2> <p>Pulastya\\\'s teachings emphasize the importance of:</p> <ul> <li><strong>Self-realization:</strong> Attaining spiritual enlightenment and self-awareness.</li> <li><strong>Dharma:</strong> Living a righteous and virtuous life.</li> <li><strong>Yoga:</strong> Practicing yoga and meditation to attain spiritual growth and self-realization.</li> </ul> <h2>Legacy and Influence</h2> <p>Pulastya\\\'s legacy continues to inspire seekers of truth and self-realization. His teachings and philosophy have had a profound impact on Hindu mythology, Vedic literature, and spirituality.</p> <h2>Interesting Facts</h2> <ul> <li><strong>Name Meaning:</strong> The name <em>\\\"Pulastya\\\"</em> means \\\"son of Pulatsu\\\" in Sanskrit.</li> <li><strong>Association with Vishnu:</strong> Pulastya is often associated with <em>Lord Vishnu</em>, the Hindu god of preservation, and is said to have possessed the power to communicate with him.</li> <li><strong>Mention in Ramayana:</strong> Pulastya is mentioned in the <em>Ramayana</em>, one of the most sacred texts of Hinduism.</li> </ul>', 'Pulastya.jpg'),
(10, 'Gautam ', 'gautam', '&lt;h1&gt;Gautam - The Revered Sage&lt;/h1&gt;', '<p>Gautam is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian mythology and Vedic literature.</p> <h2>Life and Legends</h2> <p>Gautam was a powerful sage who lived in ancient India. He was a <strong>Brahmarishi</strong> (a sage with divine powers) and was known for his extraordinary spiritual abilities.</p> <h2>Contributions</h2> <ul> <li><strong>Vedic Literature:</strong> Gautam is credited with composing several hymns and verses in the <em>Rigveda</em>, one of the most sacred texts of Hinduism.</li> <li><strong>Gautam Gotra:</strong> He is associated with the <em>Gautam Gotra</em>, a lineage of sages and scholars known for their wisdom and spiritual powers.</li> <li><strong>Spiritual Guidance:</strong> Gautam was a spiritual guide who offered wisdom and enlightenment to seekers.</li> </ul> <h2>Teachings and Philosophy</h2> <p>Gautam\\\'s teachings emphasize the importance of:</p> <ul> <li><strong>Self-realization:</strong> Attaining spiritual enlightenment and self-awareness.</li> <li><strong>Dharma:</strong> Living a righteous and virtuous life.</li> <li><strong>Yoga:</strong> Practicing yoga and meditation to attain spiritual growth and self-realization.</li> </ul> <h2>Legacy and Influence</h2> <p>Gautam\\\'s legacy continues to inspire seekers of truth and self-realization. His teachings and philosophy have had a profound impact on Hindu mythology, Vedic literature, and spirituality.</p> <h2>Interesting Facts</h2> <ul> <li><strong>Name Meaning:</strong> The name <em>\\\"Gautam\\\"</em> means \\\"descendant of Gotama\\\" in Sanskrit.</li> <li><strong>Association with Buddha:</strong> Gautam is also the name of the historical Buddha, <em>Siddhartha Gautama</em>, who founded Buddhism.</li> <li><strong>Mention in Mahabharata:</strong> Gautam is mentioned in the <em>Mahabharata</em>, one of the most sacred texts of Hinduism.</li> </ul> <h2>Famous Descendants</h2> <ul> <li><strong>Ahalya:</strong> Gautam\\\'s wife, Ahalya, was a pious and devoted woman known for her extraordinary spiritual powers.</li> <li><strong>Shatananda:</strong> Gautam\\\'s son, Shatananda, was a powerful sage known for his wisdom and spiritual strength.</li> </ul>', 'Gautam.jpg'),
(11, 'Chyavana', 'chyavana', '&lt;h1&gt;Chyavana - The Revered Sage&lt;/h1&gt;', '<p>Chyavana is a revered sage in Hinduism, known for his extraordinary wisdom, spiritual powers, and contributions to ancient Indian mythology and Vedic literature.</p> <h2>Life and Legends</h2> <p>Chyavana was a powerful sage who lived in ancient India. He was a <strong>Brahmarishi</strong> (a sage with divine powers) and was known for his extraordinary spiritual abilities.</p> <h2>Contributions</h2> <ul> <li><strong>Vedic Literature:</strong> Chyavana is credited with composing several hymns and verses in the <em>Rigveda</em>, one of the most sacred texts of Hinduism.</li> <li><strong>Chyavana Brahma:</strong> He is associated with the <em>Chyavana Brahma</em>, a sacred text that details Vedic rituals and ceremonies.</li> <li><strong>Spiritual Guidance:</strong> Chyavana was a spiritual guide who offered wisdom and enlightenment to seekers.</li> </ul> <h2>Teachings and Philosophy</h2> <p>Chyavana\'s teachings emphasize the importance of:</p> <ul> <li><strong>Self-realization:</strong> Attaining spiritual enlightenment and self-awareness.</li> <li><strong>Dharma:</strong> Living a righteous and virtuous life.</li> <li><strong>Yoga:</strong> Practicing yoga and meditation to attain spiritual growth and self-realization.</li> </ul> <h2>Legacy and Influence</h2> <p>Chyavana\'s legacy continues to inspire seekers of truth and self-realization. His teachings and philosophy have had a profound impact on Hindu mythology, Vedic literature, and spirituality.</p> <h2>Interesting Facts</h2> <ul> <li><strong>Name Meaning:</strong> The name <em>\"Chyavana\"</em> means \"youthful\" or \"rejuvenated\" in Sanskrit.</li> <li><strong>Association with Ashvins:</strong> Chyavana is often linked to the <em>Ashvins</em>, the twin gods of Hindu mythology who are said to have restored his youth and vitality.</li> <li><strong>Mention in Mahabharata:</strong> Chyavana is mentioned in the <em>Mahabharata</em>, one of the most sacred texts of Hinduism.</li> </ul>', 'Chyavana.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `maharishis`
--
ALTER TABLE `maharishis`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `slug` (`slug`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `maharishis`
--
ALTER TABLE `maharishis`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
